name: flutter_native_screenshot_plus_example
description: "Demonstrates how to use the flutter_native_screenshot_plus plugin."
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.7.0


dependencies:
  flutter:
    sdk: flutter

  flutter_native_screenshot_plus:
    path: ../

  cupertino_icons: ^1.0.8

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true


